---

- name: yum install nova-compute
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-nova-compute
  when: inventory_hostname in groups['computer']
  tags:
    - nova-compute-installed


