---

- name: "Usermod -s /bin/bash nova"
  user:
    name: nova
    shell: /bin/bash
    state: present
    home: /var/lib/nova/
    #generate_ssh_key: yes
    #ssh_key_file: .ssh/id_rsa
  when: inventory_hostname in groups['computer']
  ignore_errors: true
  tags:
    - nova-key

- name: "Mkdir nova .ssh directory"
  file: 
    path: "{{ item.dir }}"
    state: directory
    owner: "nova"
    group: "nova"
    mode: 0700
  with_items:
    - { dir: '/var/lib/nova/.ssh' }
  when: inventory_hostname in groups['computer']
  tags:
    - nova-key


- name: "Copy User nova ssh private key"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "nova"
    group: "nova"
    mode: 0600
    backup: "yes"
  with_items:
    - { src: 'files/config', dest: '/var/lib/nova/.ssh/config'}
    - { src: 'files/id_rsa', dest: '/var/lib/nova/.ssh/id_rsa' }
  when: inventory_hostname in groups['computer']
  tags:
    - nova-key

- name: "Set authorized key from file"
  authorized_key:
    user: nova
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"
  when: inventory_hostname in groups['computer']
  tags:
    - nova-key

