---

- name: yum install keystone
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-keystone
    - httpd
    - mod_wsgi
  when: inventory_hostname in groups['keystone']
  tags:
    - keystone-install


