- name: Install mysql and set root password
  hosts: 
    - controller
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 0
  remote_user: root
  roles:
    - role: mysql
  tags:
    - mysql
