- name: Install cinder
  hosts: 
    - controller
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 0
  remote_user: root
  pre_tasks:
    - include: common-tasks/mysql-db-user.yml 
      static: no
      vars:
        user_name: "{{ cinder_mysql_user }}"
        password: "{{ cinder_mysql_password }}"
        db_name: "{{ cinder_mysql_database }}"
      when: "'controller' in group_names" 
  roles:
    - role: openstack/cinder
  vars_files:
    - defaults/cinder_all.yml
  vars:
    #extra_packages: [git, vim, wget, bash-completion, iftop, net-tools, tcpdump, gcc, postgresql, postgresql-devel, python-devel, libffi-devel, python-devel, openssl-devel,  openldap-devel]
  tags:
    - cinder
