- name: Install keystone
  hosts: 
    - controller
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 0
  remote_user: root
  pre_tasks:
    - include: common-tasks/mysql-db-user.yml 
      static: no
      vars:
        user_name: "{{ keystone_mysql_user }}"
        password: "{{ keystone_mysql_password }}"
        db_name: "{{ keystone_mysql_database }}"
      when: inventory_hostname == groups['mysql'][0] 

  roles:
    - role: openstack/keystone
  vars_files:
    - defaults/keystone_all.yml
  tags:
    - keystone
