- name: Install nova
  hosts: 
    - controller
    #- computer
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 0
  remote_user: root
  pre_tasks:
    - include: common-tasks/mysql-db-user.yml 
      static: no
      vars:
        user_name: "{{ nova_mysql_user }}"
        password: "{{ nova_mysql_password }}"
        db_name: "{{ nova_mysql_database }}"
      when: "'controller' in group_names" 
    - include: common-tasks/mysql-db-user.yml 
      static: no
      vars:
        user_name: "{{ nova_api_mysql_user }}"
        password: "{{ nova_api_mysql_password }}"
        db_name: "{{ nova_api_mysql_database }}"
      when: "'controller' in group_names" 
  roles:
    - role: hostname
    #- role: system/yum
    #- role: ntp
    - role: openstack/nova
  vars_files:
    - defaults/nova_all.yml
  vars:
    hostname_prefix: "{{ ('controller' in group_names ) | ternary('controller', 'computer') }}"
    hostname_postfix: "WH"
    hostname_var: "{{ hostname_prefix ~ '-' ~ ansible_default_ipv4['address'].replace('.', '-') ~ '-' ~ hostname_postfix }}"
    ntp_server: "10.201.121.10"
    extra_repository: ["epel-release", "centos-release-openstack-{{ openstack_release }}"]
    #extra_packages: [git, vim, wget, bash-completion, iftop, net-tools, tcpdump, gcc, postgresql, postgresql-devel, python-devel, libffi-devel, python-devel, openssl-devel,  openldap-devel]
    extra_packages: [git, vim, wget, bash-completion, iftop, net-tools, tcpdump, telnet]
  tags:
    - nova
