- name: Install rabbitmq and add user
  hosts: 
    - controller
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 0
  remote_user: root
  roles:
    - role: "rabbitmq"
  tags:
    - test
