---
- name: init
  hosts: [10.201.121.10]
  roles:
    - role: system/yum
  vars:
    hostname_prefix: "{{ ('controller' in group_names ) | ternary('controller', 'computer') }}"
    hostname_postfix: "WH"
    hostname_var: "{{ hostname_prefix ~ '-' ~ ansible_default_ipv4['address'].replace('.', '-') ~ '-' ~ hostname_postfix }}"
    ntp_server: "10.201.121.10"
    extra_repository: ["epel-release", "centos-release-openstack-{{ openstack_release }}"]
    #extra_packages: [git, vim, wget, bash-completion, iftop, net-tools, tcpdump, gcc, postgresql, postgresql-devel, python-devel, libffi-devel, python-devel, openssl-devel,  openldap-devel]
    extra_packages: [git, vim, wget, bash-completion, iftop, net-tools, tcpdump, telnet]

