- name: Configure tmux
  hosts: 
    #- controller
    #- computer
    - test
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  remote_user: root
  roles:
    - role: "tmux"
  tags:
    - tmux
