- name: Configure vim
  hosts: 
    - test
  gather_facts: "{{ gather_facts | default(True) }}"
  #gather_facts: no
  max_fail_percentage: 20
  remote_user: root
  roles:
    - role: system/apt
    - role: "vim"
  vars:
    kvim_dir: /usr/local/src/kvim
    os_version: 'Debian'
  tags:
    - vim
