---
# tasks file for roles/memcached
- name: Install memcached
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - memcached
    - python-memcached

- name: Configure /etc/sysconfig/memcached
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
    backup: yes


- name: Start memcached
  systemd:
    name: memcached
    state: restarted
    enabled: true


