---

- name: yum install openstack-neutron-openvswitch
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-neutron-openvswitch
    - ebtables
    - ipset
  when: inventory_hostname in groups['computer']
  tags:
    - neutron-openvswitch-installed


