---

- name: Generate neutron config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "{{ neutron_developer_mode | bool | ternary('root', 'neutron') }}"
    mode: "0640"
    backup: "yes"
  with_items:
    - src: "{{ neutron_conf_template }}"
      dest: "{{ neutron_conf_path ~ '/neutron.conf'}}"
    - src: "{{ ml2_conf_template }}"
      dest: "{{ neutron_conf_path ~ '/plugins/ml2/openvswitch_agent.ini'}}"
    - src: "{{ ml2_conf_template }}"
      dest: "{{ neutron_conf_path ~ '/plugins/ml2/ml2_conf.ini'}}"
      #- src: "linuxbridge_agent.ini.j2"
      #dest: "{{ neutron_conf_path ~ '/plugins/linuxbridge_agent.ini'}}"
    - src: "metadata_agent.ini.j2"
      dest: "{{ neutron_conf_path ~ '/metadata_agent.ini' }}"
    - src: "dhcp_agent.ini.j2"
      dest: "{{ neutron_conf_path ~ '/dhcp_agent.ini' }}"
  tags:
    - neutron-config
    - neutron-post-install

